version: '3.1'
########## SERVICES ########
services:

###### Watchtower allows for automatically updating and restarting containers
    watchtower:
      image: v2tec/watchtower:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
      command: --interval 360 --label-enable --cleanup
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        - TZ=${TZ}
      restart: always

###### HBmonitoring
    hbmonitoring:
      image: extremeshok/hbmonitoring:latest
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        - TZ=${TZ:-UTC}
        - HB_URL=${HB_URL:-}
        - HB_USERNAME=${HB_USERNAME:-}
        - HB_PASSWORD=${HB_PASSWORD:-}
      ports:
        - 8082:8082
      restart: always
