version: '3.1'
########## SERVICES ########
services:

###### Watchtower allows for automatically updating and restarting containers
    watchtower:
      image: v2tec/watchtower:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
      command: --interval 360 --label-enable --cleanup
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        - TZ=${TZ}
      restart: always

###### Mongodb
    mongodb:
      image: mongo:4.2
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - ./data/db:/data/db
      restart: always

###### HBmonitoring
    hbmonitoring:
      image: extremeshok/hbmonitoring:latest
      depends_on:
        - mongodb
      links:
        - mongodb
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        - TZ=${TZ:-UTC}
        - MONGO_HOST=${MONGO_HOST:-mongodb}
        - MONGO_PORT=${MONGO_PORT:-27017}
        - HB_URL=${HB_URL}
        - HB_USERNAME=${HB_USERNAME}
        - HB_PASSWORD=${HB_PASSWORD}
      ports:
        - 8082:8082
      restart: always
